### PR TITLE
Complete scaffolding, passed db, server tests for Price and Promo Svc

### PR DESCRIPTION
**Pull request by LachelleF**

### CODE REVIEW

**Comment by LachelleF** [comment]
Hmmm, I didn't do that in previous executions. Will double check on my end.

**Comment by Chris-Hesterman** [comment]
still a bit curious about the mongoose docs saying what they are saying. it's oddly misleading

**Comment by LachelleF** [comment]
Merging PR

**Comment by Chris-Hesterman** [comment]
Yes I was wrong about res.end() and apparently mongo, I usually treat the connection like a promise.

**Pull request merged**
